# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

variable "project" {
  type    = string
  default = "${env("GOOGLE_PROJECT_ID")}"
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "googlecompute" "autogenerated_1" {
  image_name          = "%s"
  project_id          = "${var.project}"
  source_image_family = "%s"
  ssh_username        = "packer"
  zone                = "us-central1-a"
  image_architecture  = "%s"
  machine_type        = "%s"
}

build {
  sources = ["source.googlecompute.autogenerated_1"]
}
