# Copyright IBM Corp. 2013, 2025
# SPDX-License-Identifier: MPL-2.0


variable "project" {
  type    = string
  default = "${env("GOOGLE_PROJECT_ID")}"
}

variable "service_account_file" {
  type    = string
  default = "${env("GOOGLE_APPLICATION_CREDENTIALS")}"
}

variable "ssh_private_key" {
  type    = string
  default = ""
}

variable "ssh_username" {
  type    = string
  default = "packer"
}

variable "zone" {
  type    = string
  default = "us-central1-a"
}

variable "network_ip" {
  type    = string
  default = ""
}

variable "network" {
  type    = string
  default = ""
}

variable "image_name" {
  type    = string
  default = "packer-ip-tester"
}

locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

source "googlecompute" "autogenerated_1" {
  image_name          = "${var.image_name}"
  project_id          = "${var.project}"
  source_image_family = "centos-stream-9"
  ssh_username        = "${var.ssh_username}"
  zone                = "${var.zone}"
  network_ip          = "${var.network_ip}"
}

build {
  sources = ["source.googlecompute.autogenerated_1"]

  provisioner "shell" {
    execute_command = "sudo -E -S sh '{{ .Path }}'"
    inline          = ["ls /var/log"]
  }

  provisioner "shell" {
    inline = ["hostname -I"]
  }
}
